version: '3.8'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - TCP_IP=${TCP_IP}  # Use environment variables from the shell or .env file
      - TCP_PORT=${TCP_PORT}
